name: Windows .exe Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build using gradlew.bat
        run: .\gradlew.bat assembleDebug

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: '**/*.exe'
